#!/bin/bash

while true ; do
if ifconfig wlan0 | grep -q "inet addr:" ; then
sleep 60
else
echo "No network connection, restarting wlan0"
/sbin/ifdown 'wlan0'
sleep 10
/sbin/ifup --force 'wlan0'
sleep 20
fi
done
